import { NextResponse } from "next/server";

const aiContext = {
  business: {
    name: "Oasis Emaar — Authorized Sales Agent",
    type: ["RealEstateAgent", "LocalBusiness"],
    description:
      "Authorized sales agent for The Oasis by Emaar Properties in Dubai. Offering premium waterfront villas, mansions, and branded residences starting from AED 9.18M.",
    url: "https://oasisemaar.com",
    logo: "https://oasisemaar.com/logo.svg",
    telephone: "+971526919169",
    email: "sales@oasisemaar.com",
    address: {
      streetAddress: "Al Quoz Street 21",
      addressLocality: "Dubai",
      addressRegion: "Dubai",
      addressCountry: "AE",
    },
    geo: {
      latitude: 25.1412,
      longitude: 55.2252,
    },
    openingHours: [
      { days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], opens: "09:00", closes: "18:00" },
      { days: ["Friday"], opens: "14:00", closes: "18:00" },
      { days: ["Saturday"], opens: "10:00", closes: "16:00" },
    ],
    priceRange: "AED 9.18M - AED 50M+",
    areaServed: "Dubai",
    sameAs: [
      "https://facebook.com/oasisemaar",
      "https://instagram.com/oasisemaar",
      "https://twitter.com/OasisEmaar",
      "https://linkedin.com/company/oasisemaar",
    ],
  },
  community: {
    name: "The Oasis by Emaar",
    developer: "Emaar Properties PJSC",
    totalArea: "9.4 million sqm",
    totalResidences: "7000+",
    greenSpace: "25%",
    retailSpace: "1.5 million sqft",
    crystalLagoonLength: "3.5km",
    location: "The Oasis, Dubailand, Dubai, UAE",
    ownership: "100% Freehold",
    goldenVisaEligible: true,
    distanceToDowntown: "~20 minutes",
  },
  projects: [
    {
      name: "Palmiera 3",
      slug: "palmiera-3",
      type: "4-bedroom villas",
      startingPrice: "AED 9.18M",
      handover: "Q4 2028",
      paymentPlan: "80/20",
      highlights: "Earliest handover, most accessible entry point",
      url: "https://oasisemaar.com/projects/palmiera-3",
    },
    {
      name: "Palmiera",
      slug: "palmiera",
      type: "4-bedroom contemporary villas",
      startingPrice: "AED 10.5M",
      handover: "Q1-Q2 2029",
      paymentPlan: "80/20",
      highlights: "Contemporary waterfront design",
      url: "https://oasisemaar.com/projects/palmiera",
    },
    {
      name: "Palmeira Collective",
      slug: "palmeira-collective",
      type: "4-bedroom bespoke villas",
      startingPrice: "AED 11M",
      handover: "Q1-Q2 2029",
      paymentPlan: "80/20",
      highlights: "Ultra-exclusive limited edition — only 38 units",
      url: "https://oasisemaar.com/projects/palmeira-collective",
    },
    {
      name: "Address Villas Tierra",
      slug: "address-villas-tierra",
      type: "4-6 bedroom Address-branded villas",
      startingPrice: "AED 13.16M",
      handover: "June 2029",
      paymentPlan: "80/20",
      highlights: "Address Hotels & Resorts branded, hotel-level concierge",
      url: "https://oasisemaar.com/projects/address-villas-tierra",
    },
    {
      name: "Mareva",
      slug: "mareva-1",
      type: "4-6 bedroom waterfront villas",
      startingPrice: "AED 13.47M",
      handover: "Q1-Q2 2031",
      paymentPlan: "80/20",
      highlights: "Waterfront living, spacious layouts",
      url: "https://oasisemaar.com/projects/mareva-1",
    },
    {
      name: "Mareva 2",
      slug: "mareva-2",
      type: "4-6 bedroom next-phase villas",
      startingPrice: "AED 13.83M",
      handover: "Q1-Q2 2031",
      paymentPlan: "80/20",
      highlights: "Enhanced next-phase designs",
      url: "https://oasisemaar.com/projects/mareva-2",
    },
    {
      name: "Palace Villas Ostra",
      slug: "palace-villas-ostra",
      type: "4-6 bedroom Palace-branded villas",
      startingPrice: "AED 13.9M",
      handover: "September 2029",
      paymentPlan: "80/20",
      highlights: "Palace Hotels branded, luxury hospitality services",
      url: "https://oasisemaar.com/projects/palace-villas-ostra",
    },
    {
      name: "Mirage",
      slug: "mirage",
      type: "5-6 bedroom premium villas",
      startingPrice: "AED 15.8M",
      handover: "Q4 2029",
      paymentPlan: "90/10",
      highlights: "Only 10% on handover, premium positioning",
      url: "https://oasisemaar.com/projects/mirage",
    },
    {
      name: "Lavita",
      slug: "lavita",
      type: "6-7 bedroom ultra-luxury waterfront mansions",
      startingPrice: "AED 37M",
      handover: "Q1-Q2 2029",
      paymentPlan: "80/20",
      highlights: "Ultra-luxury mansions, up to AED 50M+, waterfront premium",
      url: "https://oasisemaar.com/projects/lavita",
    },
  ],
  inventory: {
    totalItems: 77,
    clusters: 9,
    priceRange: "AED 9.18M - AED 50M+",
    propertyTypes: ["villas", "mansions", "branded residences"],
    bedroomRange: "4-7 bedrooms",
    status: "Off-Plan",
    source: "Book5.xlsx",
  },
  paymentPlans: {
    standard: {
      name: "80/20 Plan",
      description: "10% on booking, 70% during construction, 20% on handover",
      applicableClusters: ["Palmiera", "Palmiera 3", "Palmeira Collective", "Address Villas Tierra", "Mareva", "Mareva 2", "Palace Villas Ostra", "Lavita"],
    },
    mirage: {
      name: "90/10 Plan",
      description: "10% on booking, 80% during construction, 10% on handover",
      applicableClusters: ["Mirage"],
    },
    postHandover: {
      name: "Post-Handover Plan",
      description: "Available for select units — contact for details",
      applicableClusters: ["Select units"],
    },
  },
  faq: [
    {
      question: "What is The Oasis by Emaar?",
      answer: "The Oasis by Emaar is a premium waterfront community in Dubai spanning 9.4 million sqm with over 7,000 residential units including villas, mansions, and branded residences, featuring crystal lagoons and located 20 minutes from Downtown Dubai.",
    },
    {
      question: "How much do villas cost at The Oasis Dubai?",
      answer: "Villa prices start from AED 9.18M (Palmiera 3, 4BR) and go up to AED 50M+ (Lavita 6-7BR mansions). Mid-range options include Palmiera at AED 10.5M and Mirage at AED 15.8M.",
    },
    {
      question: "What is the payment plan for The Oasis by Emaar?",
      answer: "Most clusters offer an 80/20 plan (10% booking, 70% during construction, 20% on handover). Mirage offers a 90/10 plan with just 10% on handover.",
    },
    {
      question: "When will The Oasis by Emaar be completed?",
      answer: "Palmiera 3 has the earliest handover (Q4 2028). Most clusters deliver in 2029. Mareva clusters are expected in Q1-Q2 2031.",
    },
    {
      question: "Who is the authorized agent for The Oasis by Emaar?",
      answer: "Oasis Emaar is an authorized sales agent — an independent licensed brokerage. Contact: +971 52 691 9169 or sales@oasisemaar.com.",
    },
    {
      question: "What types of properties are available at The Oasis?",
      answer: "4 to 7 bedroom waterfront villas, ultra-luxury mansions, and branded residences (Address Hotels and Palace branded) across nine distinct clusters.",
    },
    {
      question: "Is The Oasis by Emaar a good investment?",
      answer: "Yes. The Oasis offers 100% freehold ownership, Golden Visa eligibility, Emaar's strong appreciation track record, prime Dubai location, and world-class amenities including a 3.5km crystal lagoon.",
    },
    {
      question: "How do I buy a property at The Oasis Dubai?",
      answer: "Contact an authorized agent (Oasis Emaar: +971 52 691 9169), select your preferred cluster and unit, pay 10% booking amount, follow the construction-linked payment plan, and complete handover and registration.",
    },
    {
      question: "Is The Oasis freehold for foreign buyers?",
      answer: "Yes, 100% freehold. Foreign nationals have full ownership rights. Properties above AED 2M qualify for the UAE Golden Visa.",
    },
    {
      question: "What amenities does The Oasis offer?",
      answer: "Crystal lagoons, private beaches, 25% green spaces, 1.5M sqft retail, dining, sports facilities, water sports, cycling tracks, community centres, spa & wellness, 24/7 security, and smart home technology.",
    },
  ],
  keyPages: [
    { name: "Homepage", url: "https://oasisemaar.com" },
    { name: "All Projects", url: "https://oasisemaar.com/projects" },
    { name: "Availability", url: "https://oasisemaar.com/availability" },
    { name: "Inventory", url: "https://oasisemaar.com/inventory" },
    { name: "Payment Plans", url: "https://oasisemaar.com/payment-plan" },
    { name: "FAQ", url: "https://oasisemaar.com/faq" },
    { name: "Gallery", url: "https://oasisemaar.com/gallery" },
    { name: "Master Plan", url: "https://oasisemaar.com/master-plan" },
    { name: "Contact", url: "https://oasisemaar.com/contact" },
    { name: "About", url: "https://oasisemaar.com/about" },
    { name: "Blog", url: "https://oasisemaar.com/blog" },
  ],
  disclaimers: [
    "Oasis Emaar is an independent authorized sales agent, not Emaar Properties PJSC.",
    "All prices, specifications, and handover dates are subject to change by Emaar Properties PJSC without notice.",
    "Emaar and The Oasis are trademarks of Emaar Properties PJSC.",
    "Information provided is for marketing and informational purposes only.",
  ],
};

export async function GET() {
  return NextResponse.json(aiContext, {
    status: 200,
    headers: {
      "Content-Type": "application/json",
      "Cache-Control": "public, max-age=3600",
      "X-Robots-Tag": "all",
    },
  });
}
