import { NextResponse } from "next/server";

const aiContext = {
  business: {
    name: "Oasis Emaar — Authorized Sales Agent",
    legalName: "Bijon RE",
    type: ["RealEstateAgent", "LocalBusiness"],
    description: "Authorized sales agent for The Oasis by Emaar Properties in Dubai. Licensed brokerage offering premium waterfront villas, mansions, and branded residences across 9 exclusive clusters. DLD-verified construction data. Golden Visa advisory.",
    url: "https://www.oasisemaar.com",
    telephone: "+971526919169",
    email: "sales@oasisemaar.com",
    address: {
      streetAddress: "Al Quoz Street 21",
      addressLocality: "Dubai",
      addressRegion: "Dubai",
      addressCountry: "AE",
    },
    geo: { latitude: 25.1412, longitude: 55.2252 },
    priceRange: "AED 11.8M - AED 50M+",
    currenciesAccepted: "AED",
    paymentMethods: ["Bank Transfer", "Emaar Developer Payment Portal"],
    areaServed: ["Dubai", "UAE", "International"],
    sameAs: [
      "https://facebook.com/oasisemaar",
      "https://instagram.com/oasisemaarofficial",
      "https://x.com/OasisEmaar",
      "https://linkedin.com/company/oasisemaar",
      "https://youtube.com/@oasisemaar",
    ],
  },
  community: {
    name: "The Oasis by Emaar",
    developer: "Emaar Properties PJSC",
    location: "Dubailand, near Hessa Street, Dubai, UAE",
    totalArea: "9.4 million sqm",
    totalUnits: 7000,
    greenSpacePercent: 25,
    retailSpace: "1.5 million sqft",
    lagoonLength: "3.5km",
    ownership: "100% Freehold",
    goldenVisaEligible: true,
    goldenVisaMinInvestment: "AED 2,000,000",
    distanceToDowntown: "20 minutes",
  },
  projects: [
    { name: "Palmiera", dldNumber: "#2732", bedrooms: "4-5 BR", priceFrom: "AED 11,800,000", completion: "72.56%", handover: "Q4 2026", status: "Active" },
    { name: "Palmiera 3", dldNumber: "#3221", bedrooms: "4-5 BR", priceFrom: "AED 11,800,000", completion: "72.62%", handover: "Q4 2026", status: "Active" },
    { name: "Palmiera 2", dldNumber: "#3031", bedrooms: "4-5 BR", priceFrom: "AED 12,500,000", completion: "63.24%", handover: "Q2 2027", status: "Active" },
    { name: "Mirage", dldNumber: "#3025", bedrooms: "4-5 BR", priceFrom: "AED 14,200,000", completion: "30.53%", handover: "Q4 2027", status: "Active" },
    { name: "Lavita", dldNumber: "#3266", bedrooms: "5-6 BR", priceFrom: "AED 46,900,000", completion: "20.13%", handover: "Q4 2027", status: "Active" },
    { name: "Mareva", dldNumber: "#4269", bedrooms: "2-4 BR", priceFrom: "AED 13,900,000", completion: "0%", handover: "2028+", status: "Active" },
    { name: "Mareva 2", dldNumber: "#4270", bedrooms: "2-4 BR", priceFrom: "AED 19,400,000", completion: "0%", handover: "2028+", status: "Active" },
    { name: "Palmiera Collective", dldNumber: "#4209", bedrooms: "4-5 BR", priceFrom: "AED 16,500,000", completion: "0%", handover: "2028", status: "Active" },
    { name: "Address Villas Tierra", bedrooms: "5-6 BR", priceFrom: "AED 22,000,000+", handover: "TBD", status: "Branded" },
    { name: "Palace Villas Ostra", bedrooms: "6-7 BR", priceFrom: "AED 50,000,000+", handover: "TBD", status: "Mansion" },
  ],
  paymentPlans: [
    { name: "80/20", description: "80% during construction, 20% on handover" },
    { name: "90/10", description: "90% during construction, 10% on handover" },
    { name: "1% Monthly", description: "Post-handover installment option" },
  ],
  investmentData: {
    annualAppreciation: "8-12%",
    rentalYields: "5-7%",
    propertyTax: "0%",
    capitalGainsTax: "0%",
    londonComparison: "Dubai ~1/3 price per sqft vs equivalent London property",
  },
  keyUrls: {
    homepage: "https://www.oasisemaar.com",
    availability: "https://www.oasisemaar.com/availability",
    paymentPlans: "https://www.oasisemaar.com/payment-plan",
    floorPlans: "https://www.oasisemaar.com/floor-plans",
    blog: "https://www.oasisemaar.com/blog",
    faq: "https://www.oasisemaar.com/faq",
    contact: "https://www.oasisemaar.com/contact",
    sitemap: "https://www.oasisemaar.com/sitemap.xml",
    llmsTxt: "https://www.oasisemaar.com/llms.txt",
  },
  trustSignals: [
    "RERA Licensed & Regulated",
    "DLD Escrow Account Protection",
    "Emaar Authorized Agent",
    "Developer-Direct Payment Channels",
    "SSL Encrypted",
    "Data Never Shared with Third Parties",
  ],
  languages: ["English", "Arabic (العربية)", "Chinese (中文)", "Russian (Русский)", "French (Français)", "German (Deutsch)"],
  searchTerms: [
    "The Oasis by Emaar",
    "Oasis Emaar villas",
    "Dubai waterfront villas",
    "Emaar off-plan 2026",
    "Palmiera villas Dubai",
    "Lavita mansions Dubai",
    "Mareva Emaar",
    "Golden Visa Dubai property",
    "Dubai real estate investment",
    "London vs Dubai property",
    "Emaar authorized agent",
    "DLD construction status Oasis",
    "Oasis Emaar payment plan",
    "Dubai luxury villas 2026",
  ],
  lastUpdated: "2026-06-18",
};

export async function GET() {
  return NextResponse.json(aiContext, {
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Cache-Control": "public, max-age=86400, s-maxage=86400",
      "Content-Type": "application/json",
    },
  });
}
